[package]
name = "cucumber"
version = "0.1.0"
authors = ["Brendan Molloy <brendan@bbqsrc.net>"]

[lib]
harness = false

[dependencies]
gherkin = { git = "https://github.com/bbqsrc/gherkin-rust.git", branch = "master" }
regex = "^1.0"
