name: Book

on:
  pull_request:
    paths:
      - 'book/**'
  push:
    paths:
      - 'book/**'

jobs:

  ###########
  # Testing #
  ###########

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - run: make test.book




  ##############
  # Deployment #
  ##############

  deploy:
    needs: [tests]
#    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: peaceiris/actions-mdbook@v1

      - run: make book.build out=gh-pages/master

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          keepFiles: true
          publish_dir: book/gh-pages
